baseURL = 'https://example.org/'
languageCode = 'ml-in'
title = "ബാബുവിന്റെ ഗാനശേഖരം."
theme = 'typo'
publishDir = "docs"
disableKinds = ["RSS"]

[taxonomies]
tag = 'tags'

[params]
description = "Songs"

theme = 'dark'
colorPalette = 'base16-default'
hideHeader = false
showFooter = true
hideBackToTop = true

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = ''

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "Home"

# Main menu pages
[[params.menu]]
name = "എന്നെപ്പറ്റി"
url = "/about"

[markup]
[markup.highlight]
style = 'algol'
  [markup.goldmark]
    [markup.goldmark.renderer]
          hardWraps = true
          unsafe = true
