baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "ഗാനങ്ങൾ"
theme = 'typo'
publishDir = "docs"

[taxonomies]
tag = 'tags'

[params]
description = "Songs"

theme = 'dark'
colorPalette = 'base16-default'
hideHeader = false
showFooter = false

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = ''

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "Home"

# Main menu pages
[[params.menu]]
name = "പ്രാരംഭതാൾ"
url = "/"

[[params.menu]]
name = "വിഭാഗങ്ങൾ"
url = "/tags"

[[params.menu]]
name = "എന്നെപ്പറ്റി"
url = "/about"

[markup]
[markup.highlight]
style = 'algol'
  [markup.goldmark]
    [markup.goldmark.renderer]
          hardWraps = true
          unsafe = true
